// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdRee8sAwSqhsZ43mkH6TBCLCxHEp1Ov4',
    appId: '1:456500666849:web:9e2d0f53219f3c92f872a0',
    messagingSenderId: '456500666849',
    projectId: 'crypthera-app',
    authDomain: 'crypthera-app.firebaseapp.com',
    storageBucket: 'crypthera-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtDsOF-3bNaqig5oXChvayl35wtsnuQoE',
    appId: '1:456500666849:android:b50535cfe338c2ecf872a0',
    messagingSenderId: '456500666849',
    projectId: 'crypthera-app',
    storageBucket: 'crypthera-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfqAxmdwHw6Ih-hD4efpTW57x-Wykqzb0',
    appId: '1:456500666849:ios:3701f3347fcfcdbaf872a0',
    messagingSenderId: '456500666849',
    projectId: 'crypthera-app',
    storageBucket: 'crypthera-app.firebasestorage.app',
    iosBundleId: 'com.example.crypthera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqAxmdwHw6Ih-hD4efpTW57x-Wykqzb0',
    appId: '1:456500666849:ios:3701f3347fcfcdbaf872a0',
    messagingSenderId: '456500666849',
    projectId: 'crypthera-app',
    storageBucket: 'crypthera-app.firebasestorage.app',
    iosBundleId: 'com.example.crypthera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdRee8sAwSqhsZ43mkH6TBCLCxHEp1Ov4',
    appId: '1:456500666849:web:e20c0f7384831423f872a0',
    messagingSenderId: '456500666849',
    projectId: 'crypthera-app',
    authDomain: 'crypthera-app.firebaseapp.com',
    storageBucket: 'crypthera-app.firebasestorage.app',
  );
}
